/* Codes Autogenerated by Effinator */
using System.Reflection;
using Autofac.Integration.Mvc;

namespace GMapSample.DependencyInjection
{
    public class ControllerInstaller
    {
        public static void Install()
        {
            Bootstrapper.Builder.RegisterControllers(Assembly.GetExecutingAssembly());

        }
    }
}